version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./db:/var/lib/postgresql/data  # 將 db 目錄與 PostgreSQL 資料夾同步
    ports:
      - "5432:5432"
  
  fastapi:
    build: ./api  # 指定 api 目錄為 FastAPI 應用的路徑
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    volumes:
      - ./api:/app  # 同步 api 目錄作為應用程式代碼
      - ./gz:/app/gz  # 將 gz 目錄與 FastAPI 應用內部同步
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql+asyncpg://myuser:mypassword@postgres/mydatabase"